channels:
  - pwwang
  - conda-forge
  - r
  - bioconda
  - nodefaults
dependencies:
  # Specified in base, but need to repeat here to avoid PackagesNotFoundError
  - pwwang::bioconductor-screpertoire=2.2
  - r-biopipen.utils=0.3.4=r43_3
  - r-scplotter=0.6.4=r43_2
  - r-plotthis=0.9.0=r43_1
  - r-enrichit=0.0.4=r43_1
  - r-gglogger=0.1.6=r43_1
